Update utils.py
```intelmqctl --type json check``` (as executed by intelmq-manager) fails on RETURN_TYPE == 'json': because setup_list_logging does not return the required iterable:
```
Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqctl')()
  File "/opt/intelmq.git/intelmq/bin/intelmqctl.py", line 1553, in main
    return x.run()
  File "/opt/intelmq.git/intelmq/bin/intelmqctl.py", line 936, in run
    retval, results = args.func(**args_dict)
  File "/opt/intelmq.git/intelmq/bin/intelmqctl.py", line 1286, in check
    logging_level=self.logging_level)
TypeError: 'NoneType' object is not iterable
```
Which breaks intelmq-manager check page.