Revert "BUG: lib/bot: reload harm on sighup"
This reverts commit 329005774e1bfea9ed844c7166f93998c1eae3ec.

Probably causes this bug:
2016-09-20 16:33:24,810 - rt-opentftp - ERROR - Bot has found a problem.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 154, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/collectors/rt/collector_rt.py", line 84, in process
    report = Report()
  File "/home/aaron/intelmq/intelmq/lib/message.py", line 294, in __init__
    super(Report, self).__init__(message, auto)
TypeError: super(type, obj): obj must be an instance or subtype of type